data_loading:
        data_path: 
            value: "../GeneralDatasets/sanitizer_output/german_credit/full_A=1-No=1--E=10.csv" # "../GeneralDatasets/Csv/Adult_NoCat"
            desc: "Where to get the input dataset"
        label_path:
            value: "../GeneralDatasets/sanitizer_output/german_credit/labels_A=1-No=1--E=10.csv"
            desc: "Where labels are. Line by line equivalent to data"
model_params:
        batchSize: 
            value: 32
            desc: "Size of training batch size"
        test_batch_size: 
            value: 128
            desc: "Size of testing batch size. Ususally as big as memory allows"
        percent_train_set: 
            value: 0.85
            desc: "Percentage of total dataset used as training set. Rest goes into test set"
        learning_rate:
            value: 0.01
            desc: "Learning rate `lr` for model training"
        num_epochs:
            value: 25
            desc: "Number of epochs to train the model."
        