data_loading:
        path: 
              value: "../GeneralDatasets/sanitizer_output/german_credit/n=1_alpha-gr-0.9" # "../GeneralDatasets/Csv/Adult_NoCat"
              desc: "Where to get the input dataset"
model_params:
        batchSize: 
              value: 32
              desc: "Size of training batch size"
        test_batch_size: 
              value: 128
              desc: "Size of testing batch size. Ususally as big as memory allows"
        percent_train_set: 
              value: 0.85
              desc: "Percentage of total dataset used as training set. Rest goes into test set"