data_loading:
        data_path: 
            value: "./data/disp_impact_remover_0.9.csv"
            desc: "Where to get the input dataset"
        label_path:
            value: "./data/disp_impact_remover_og.csv"
            desc: "Where labels are. Line by line equivalent to data"
model_params:
        col_to_del:
            value: 'sex'
            desc: "Column to remove from training data. Considered 'sensitive' and assumed to be hidden."
        
